name: "GitHub Actions"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  ddy:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai  # 设置时区为亚洲/上海
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Working"
        timeout-minutes: 360
        run: bash update.sh

      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain)" ]; then
            git commit -a -m "⌚️$(date +%Y%m%d%H%M%S)"
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "No changes to commit"
            echo "changes=false" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Push changes
        if: env.changes == 'true'
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
        shell: bash
